spring:
  security:
    oauth2:
      client:
        registration:
          intra42:
            client-name: intra42
            client-id: "${UID_42INTRA}"
            client-secret: "${SECRET_42INTRA}"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: public

        provider:
          intra42:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            user-info-uri: https://api.intra.42.fr/v2/me
            token-uri: https://api.intra.42.fr/oauth/token
            user-name-attribute: id